export default [
  {
    // 8.15.3: 必须显式忽略——此前无 ignores，`eslint .` 会去 lint vendor/ 下的压缩库
    // （xlsx.full.min.js 951KB），实测 193978 problems / 20635 errors 全是噪音，
    // 真正的 error 被淹没，lint.sh 长期红着形同虚设。.prettierignore 早已忽略这些。
    ignores: [
      'vendor/**',
      'cache/**',
      '.cache/**',
      'node_modules/**',
      '**/*.min.js',
      '**/*.min.css',
    ],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        fetch: 'readonly',
        XMLHttpRequest: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        AbortController: 'readonly',
        Symbol: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        Proxy: 'readonly',
        Reflect: 'readonly',
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        Date: 'readonly',
        RegExp: 'readonly',
        Error: 'readonly',
        TypeError: 'readonly',
        RangeError: 'readonly',
        JSON: 'readonly',
        Math: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        encodeURIComponent: 'readonly',
        decodeURIComponent: 'readonly',
        encodeURI: 'readonly',
        decodeURI: 'readonly',
        escape: 'readonly',
        unescape: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        performance: 'readonly',
        crypto: 'readonly',
        location: 'readonly',
        history: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        indexedDB: 'readonly',
        getComputedStyle: 'readonly',
        matchMedia: 'readonly',
        scrollBy: 'readonly',
        scrollTo: 'readonly',
        Element: 'readonly',
        HTMLElement: 'readonly',
        Node: 'readonly',
        NodeList: 'readonly',
        HTMLCollection: 'readonly',
        Event: 'readonly',
        EventTarget: 'readonly',
        CustomEvent: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        TouchEvent: 'readonly',
        PointerEvent: 'readonly',
        FocusEvent: 'readonly',
        InputEvent: 'readonly',
        WheelEvent: 'readonly',
        DragEvent: 'readonly',
        ClipboardEvent: 'readonly',
        AnimationEvent: 'readonly',
        TransitionEvent: 'readonly',
        MessageEvent: 'readonly',
        StorageEvent: 'readonly',
        PopStateEvent: 'readonly',
        HashChangeEvent: 'readonly',
        PageTransitionEvent: 'readonly',
        BeforeUnloadEvent: 'readonly',
        MediaQueryListEvent: 'readonly',
        MediaQueryList: 'readonly',
        Image: 'readonly',
        Audio: 'readonly',
        Video: 'readonly',
        Canvas: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        WebGLRenderingContext: 'readonly',
        WebGL2RenderingContext: 'readonly',
        Path2D: 'readonly',
        ImageData: 'readonly',
        ImageBitmap: 'readonly',
        OffscreenCanvas: 'readonly',
        OffscreenCanvasRenderingContext2D: 'readonly',
        CanvasPattern: 'readonly',
        CanvasGradient: 'readonly',
        TextMetrics: 'readonly',
        DOMMatrix: 'readonly',
        DOMPoint: 'readonly',
        DOMRect: 'readonly',
        DOMRectReadOnly: 'readonly',
        DOMQuad: 'readonly',
        DOMStringList: 'readonly',
        DOMTokenList: 'readonly',
        DOMImplementation: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        XPathResult: 'readonly',
        XPathExpression: 'readonly',
        XPathEvaluator: 'readonly',
        TreeWalker: 'readonly',
        NodeIterator: 'readonly',
        NodeFilter: 'readonly',
        Range: 'readonly',
        StaticRange: 'readonly',
        AbstractRange: 'readonly',
        Selection: 'readonly',
        window: 'readonly',
        self: 'readonly',
        top: 'readonly',
        parent: 'readonly',
        frames: 'readonly',
        opener: 'readonly',
        closed: 'readonly',
        length: 'readonly',
        name: 'readonly',
        status: 'readonly',
        toolbar: 'readonly',
        menubar: 'readonly',
        scrollbars: 'readonly',
        statusbar: 'readonly',
        locationbar: 'readonly',
        personalbar: 'readonly',
        directories: 'readonly',
        screen: 'readonly',
        innerWidth: 'readonly',
        innerHeight: 'readonly',
        outerWidth: 'readonly',
        outerHeight: 'readonly',
        screenX: 'readonly',
        screenY: 'readonly',
        screenLeft: 'readonly',
        screenTop: 'readonly',
        pageXOffset: 'readonly',
        pageYOffset: 'readonly',
        scrollX: 'readonly',
        scrollY: 'readonly',
        clientInformation: 'readonly',
        styleMedia: 'readonly',
        visualViewport: 'readonly',
        speechSynthesis: 'readonly',
        caches: 'readonly',
        cookieStore: 'readonly',
        crossOriginIsolated: 'readonly',
        isSecureContext: 'readonly',
        origin: 'readonly',
        performance: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        fetch: 'readonly',
        createImageBitmap: 'readonly',
        structuredClone: 'readonly',
        reportError: 'readonly',
        queueMicrotask: 'readonly',
        clearImmediate: 'readonly',
        setImmediate: 'readonly',
        scheduler: 'readonly',
        queryLocalFonts: 'readonly',
        showOpenFilePicker: 'readonly',
        showSaveFilePicker: 'readonly',
        showDirectoryPicker: 'readonly',
        getScreenDetails: 'readonly',
        showDirectoryPicker: 'readonly',
        // Tampermonkey/Greasemonkey globals
        GM_xmlhttpRequest: 'readonly',
        GM_setValue: 'readonly',
        GM_getValue: 'readonly',
        GM_addStyle: 'readonly',
        GM_registerMenuCommand: 'readonly',
        GM_notification: 'readonly',
        GM_setClipboard: 'readonly',
        GM_openInTab: 'readonly',
        GM_download: 'readonly',
        GM_info: 'readonly',
        GM_getTab: 'readonly',
        GM_saveTab: 'readonly',
        GM_getTabs: 'readonly',
        GM_addValueChangeListener: 'readonly',
        GM_removeValueChangeListener: 'readonly',
        GM_log: 'readonly',
        GM_getResourceText: 'readonly',
        GM_getResourceURL: 'readonly',
        unsafeWindow: 'readonly',
        // jQuery
        $: 'readonly',
        jQuery: 'readonly'
      }
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-console': 'off',
      'no-undef': 'warn',
      'no-redeclare': 'warn',
      'no-constant-condition': 'warn',
      'no-empty': 'warn',
      'no-extra-semi': 'error',
      'no-irregular-whitespace': 'error',
      'no-unreachable': 'error',
      'curly': 'error',
      'eqeqeq': 'warn',
      'no-caller': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-wrappers': 'error',
      'no-shadow': 'warn',
      'no-with': 'error',
      'no-var': 'warn',
      'prefer-const': 'warn',
      'semi': ['error', 'always'],
      'quotes': ['warn', 'single', { avoidEscape: true }],
      'indent': ['warn', 2],
      'comma-dangle': ['warn', 'never'],
      'no-multiple-empty-lines': ['warn', { max: 2 }],
      'no-trailing-spaces': 'warn'
    }
  },
  {
    // 8.15.3: 本配置文件自身是 ESM；主配置的 sourceType:'script' 会把它判成
    // Parsing error（'import' and 'export' may appear only with 'sourceType: module'）
    files: ['eslint.config.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module'
    }
  },
  {
    // 8.15.3: Node 侧脚本（serve.js / show.js）需要 Node 全局，否则 require/__dirname/module
    // 一律报 no-undef，把真正的问题淹掉
    files: ['serve.js', 'show.js'],
    languageOptions: {
      globals: {
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
        Buffer: 'readonly'
      }
    }
  }
];
